# Generated by Django 4.2.4 on 2023-10-30 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_products_thumbnail_alter_users_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='user',
            new_name='customer',
        ),
    ]
