# Generated by Django 4.2.4 on 2023-11-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users_role_alter_role_name'),
        ('app', '0008_remove_products_category_products_category'),
    ]

    operations = [
    ]
